import './lexical.scss';

const theme = {
  autocomplete: 'lexicalEditor-autocomplete',
  blockCursor: 'lexicalEditor-blockCursor',
  characterLimit: 'lexicalEditor-characterLimit',
  code: 'lexicalEditor-code',
  codeHighlight: {
    atrule: 'lexicalEditor-tokenAttr',
    attr: 'lexicalEditor-tokenAttr',
    boolean: 'lexicalEditor-tokenProperty',
    builtin: 'lexicalEditor-tokenSelector',
    cdata: 'lexicalEditor-tokenComment',
    char: 'lexicalEditor-tokenSelector',
    class: 'lexicalEditor-tokenFunction',
    'class-name': 'lexicalEditor-tokenFunction',
    comment: 'lexicalEditor-tokenComment',
    constant: 'lexicalEditor-tokenProperty',
    deleted: 'lexicalEditor-tokenProperty',
    doctype: 'lexicalEditor-tokenComment',
    entity: 'lexicalEditor-tokenOperator',
    function: 'lexicalEditor-tokenFunction',
    important: 'lexicalEditor-tokenVariable',
    inserted: 'lexicalEditor-tokenSelector',
    keyword: 'lexicalEditor-tokenAttr',
    namespace: 'lexicalEditor-tokenVariable',
    number: 'lexicalEditor-tokenProperty',
    operator: 'lexicalEditor-tokenOperator',
    prolog: 'lexicalEditor-tokenComment',
    property: 'lexicalEditor-tokenProperty',
    punctuation: 'lexicalEditor-tokenPunctuation',
    regex: 'lexicalEditor-tokenVariable',
    selector: 'lexicalEditor-tokenSelector',
    string: 'lexicalEditor-tokenSelector',
    symbol: 'lexicalEditor-tokenProperty',
    tag: 'lexicalEditor-tokenProperty',
    url: 'lexicalEditor-tokenOperator',
    variable: 'lexicalEditor-tokenVariable',
  },
  embedBlock: {
    base: 'lexicalEditor-embedBlock',
    focus: 'lexicalEditor-embedBlockFocus',
  },
  hashtag: 'lexicalEditor-hashtag',
  heading: {
    h1: 'lexicalEditor-h1',
    h2: 'lexicalEditor-h2',
    h3: 'lexicalEditor-h3',
    h4: 'lexicalEditor-h4',
    h5: 'lexicalEditor-h5',
    h6: 'lexicalEditor-h6',
  },
  hr: 'lexicalEditor-hr',
  hrSelected: 'lexicalEditor-hrSelected',
  image: 'editor-image',
  indent: 'lexicalEditor-indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'lexicalEditor-layoutContainer',
  layoutItem: 'lexicalEditor-layoutItem',
  link: 'lexicalEditor-link',
  list: {
    checklist: 'lexicalEditor-checklist',
    listitem: 'lexicalEditor-listItem',
    listitemChecked: 'lexicalEditor-listItemChecked',
    listitemUnchecked: 'lexicalEditor-listItemUnchecked',
    nested: {
      listitem: 'lexicalEditor-nestedListItem',
    },
    olDepth: [
      'lexicalEditor-ol1',
      'lexicalEditor-ol2',
      'lexicalEditor-ol3',
      'lexicalEditor-ol4',
      'lexicalEditor-ol5',
    ],
    ul: 'lexicalEditor-ul',
  },
  ltr: 'lexicalEditor-ltr',
  mark: 'lexicalEditor-mark',
  markOverlap: 'lexicalEditor-markOverlap',
  paragraph: 'lexicalEditor-paragraph',
  quote: 'lexicalEditor-quote',
  rtl: 'lexicalEditor-rtl',
  specialText: 'lexicalEditor-specialText',
  tab: 'lexicalEditor-tabNode',
  table: 'lexicalEditor-table',
  tableAddColumns: 'lexicalEditor-tableAddColumns',
  tableAddRows: 'lexicalEditor-tableAddRows',
  tableAlignment: {
    center: 'lexicalEditor-tableAlignmentCenter',
    right: 'lexicalEditor-tableAlignmentRight',
  },
  tableCell: 'lexicalEditor-tableCell',
  tableCellActionButton: 'lexicalEditor-tableCellActionButton',
  tableCellActionButtonContainer:
    'lexicalEditor-tableCellActionButtonContainer',
  tableCellHeader: 'lexicalEditor-tableCellHeader',
  tableCellResizer: 'lexicalEditor-tableCellResizer',
  tableCellSelected: 'lexicalEditor-tableCellSelected',
  tableFrozenColumn: 'lexicalEditor-tableFrozenColumn',
  tableFrozenRow: 'lexicalEditor-tableFrozenRow',
  tableRowStriping: 'lexicalEditor-tableRowStriping',
  tableScrollableWrapper: 'lexicalEditor-tableScrollableWrapper',
  tableSelected: 'lexicalEditor-tableSelected',
  tableSelection: 'lexicalEditor-tableSelection',
  text: {
    bold: 'lexicalEditor-textBold',
    capitalize: 'lexicalEditor-textCapitalize',
    code: 'lexicalEditor-textCode',
    highlight: 'lexicalEditor-textHighlight',
    italic: 'lexicalEditor-textItalic',
    lowercase: 'lexicalEditor-textLowercase',
    strikethrough: 'lexicalEditor-textStrikethrough',
    subscript: 'lexicalEditor-textSubscript',
    superscript: 'lexicalEditor-textSuperscript',
    underline: 'lexicalEditor-textUnderline',
    underlineStrikethrough: 'lexicalEditor-textUnderlineStrikethrough',
    uppercase: 'lexicalEditor-textUppercase',
  },
};

export default theme;
